### ISSUE TITLE
TypeError: unsupported operand types for +: "PosixPath" and "str"

### ISSUE THREAD

**Issue by dt-woods** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#174]
Failing to import fedelemflowlist version 1.1.1 due to the following error:

```py
>>> import fedelemflowlist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Envs/ebm/lib/python3.11/site-packages/fedelemflowlist/__init__.py", line 11, in <module>
    from fedelemflowlist.flowlist import read_in_flowclass_file
  File "~/Envs/ebm/lib/python3.11/site-packages/fedelemflowlist/flowlist.py", line 8, in <module>
    from fedelemflowlist.globals import log, inputpath, flow_list_specs,\
  File "~/Envs/ebm/lib/python3.11/site-packages/fedelemflowlist/globals.py", line 23, in <module>
    fedefl_path.local_path + "/fedelemflowlist/")
    ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

I solved this error in ElectricityLCI by wrapping `paths.local_path` with `str` method:

```py
paths=Paths()
paths.local_path = os.path.realpath(str(paths.local_path) + "/electricitylci")
```

https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/ff7e31667c2c559a45ae5bbbe2ec2280cd851b45/fedelemflowlist/globals.py#L23C12-L23C12

**Comment by bl-young** [comment]
do you know what version of esupy you have here? I believe v1.1.1 should align with esupy v0.2.2 where the local_path should already be a string.

But yes we have updated to use Path objects instead of strings for better cross platform consistency. There could still be minor issues to work out.

**Comment by bl-young** [comment]
Ok I saw some of your other commits - yes the problem here is using FEDEFL v1.1.1 and stewi v1.1.1.

I need to get the next release of FEDEFL out (currently on [develop ](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/tree/develop)if you want to point there for the time being) which will align them all.

This suite of updates related to the Pathlib update are generally rare so these kind of issues shouldn't crop up too often in the future.

**Comment by dt-woods** [comment]
I don't plan to use any develop branches as dependencies, so I may roll back to an earlier version of fedelemflowlist until the posix string issue is resolved.

**Comment by bl-young** [comment]
This should be resolved now with v1.1.2 let me know if you continue to run into issues
