### ISSUE TITLE
AttributeError: 'Ref' object has no attribute 'to_json' when calling `write_jsonld` with flowmappings

### ISSUE THREAD

**Issue by fjuniorr** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#184]
I'm trying to generate openLCA JSON-LD zip archive with elementary flows and flowmappings and I'm get the error "AttributeError: 'Ref' object has no attribute 'to_json'". Here a snippet reproducing the error:

```python
import fedelemflowlist
from pathlib import Path

output_path = Path('flows_w_mappings.zip')
flowlist = fedelemflowlist.get_flows(preferred_only=False)
flowlist = flowlist.iloc[0:100]
flowmapping = fedelemflowlist.get_flowmapping('ImpactWorld+')
fedelemflowlist.write_jsonld(flowlist,output_path, flowmapping)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fjunior/Projects/cauldron/Federal-LCA-Commons-Elementary-Flow-List/fedelemflowlist/__init__.py", line 79, in write_jsonld
    writer.write_to(path)
  File "/Users/fjunior/Projects/cauldron/Federal-LCA-Commons-Elementary-Flow-List/fedelemflowlist/jsonld.py", line 146, in write_to
    self._write_mappings(zw)
  File "/Users/fjunior/Projects/cauldron/Federal-LCA-Commons-Elementary-Flow-List/fedelemflowlist/jsonld.py", line 224, in _write_mappings
    mappings.append(e.to_json())
                    ^^^^^^^^^^^
  File "/Users/fjunior/Projects/cauldron/Federal-LCA-Commons-Elementary-Flow-List/fedelemflowlist/jsonld.py", line 119, in to_json
    'from': self.source_flow.to_json(),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fjunior/Projects/cauldron/Federal-LCA-Commons-Elementary-Flow-List/fedelemflowlist/jsonld.py", line 74, in to_json
    'flow': flow_ref.to_json()
            ^^^^^^^^^^^^^^^^
AttributeError: 'Ref' object has no attribute 'to_json'
```

I got the same error running the the [`run_mappings.ipynb`](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/master/Jupyter/run_mappings.ipynb) notebook locally[^20231118T080354].

[^20231118T080354]: I did not manage to make it work in Binder.

**Comment by fjuniorr** [comment]
Thanks!
